### PR TITLE
Display the app name in the authorize page

### LINKED ISSUE #177: App avatar on authorization page is wrong
Hi,

I am getting the Authorization page:

steemconnect_page

But the logo seems not working, and instead of the app id, it would be great to have the App Name:
steemconnnect_page2

Can you help?

Thanks!

### PR DESCRIPTION
**Pull request by gregory-latinier**
Use the app name when it's known and remove the character '@' because it's not the
Fix #177

### CODE REVIEW

**Comment by bonustrack** [comment]
- I still can see `null` if the name of app is empty:
image

Also we should never display an external image on steemconnect like that:
image
External image should go through steemit image proxy. Example: 
https://steemitimages.com/128x128/https://byteball.co/img/logo.jpg

**Comment by gregory-latinier** [comment]
Empty app name should not exist, that's why I update the AppForm using antd. No controls were made.
null value shouldn't have been possible in the first place.

**Comment by bonustrack** [comment]
@gregory-latinier on production db we have apps with NULL as name. That's seem to be the default value. Even if we change the default value now we should make this PR working for previous apps having NULL.

**Comment by gregory-latinier** [comment]
What do you want to display instead of null ?

**Comment by bonustrack** [comment]
When it's null we can show this text `Do you want to authorize the application with Steem account @client_id to use your posting role?`.

**Comment by bonustrack** [comment]
Deployment success but look like app failed to start. Maybe it's related to config vars change.

**Comment by bonustrack** [comment]
Can you fix CircleCi errors?

**Pull request merged**
